### ISSUE TITLE
org.springframework.jdbc.datasource.init.ScriptStatementFailedException: Failed to execute SQL script statement #8 of URL 

### ISSUE THREAD

**Issue by JavaHelper** [sivaprasadreddy/springboot-rest-api-design#2]
I see following error is coming when I run the BlogApplication.java. Please help me

```
org.springframework.jdbc.datasource.init.ScriptStatementFailedException: Failed to execute SQL script statement #8 of URL [file:/E:/Advance%20Java/GIT%20GIT%20GIT/springboot-rest-api-design/target/classes/data.sql]: insert into users(user_id, email, password, name) values(1,'admin@gmail.com','$2a$10$pCDI501CUE3lhXXN/fX7t.q735udWnsxdab9yuaM4Ss3wuilGFG/u','Administrator'); nested exception is com.mysql.jdbc.MysqlDataTruncation: Data truncation: Data too long for column 'password' at row 1
	at org.springframework.jdbc.datasource.init.ScriptUtils.executeSqlScript(ScriptUtils.java:486) ~[spring-jdbc-4.2.1.RELEASE.jar:4.2.1.RELEASE]
	at org.springframework.jdbc.datasource.init.ResourceDatabasePopulator.populate(ResourceDatabasePopulator.java:229) ~[spring-jdbc-4.2.1.RELEASE.jar:4.2.1.RELEASE]
	at org.springframework.jdbc.datasource.init.DatabasePopulatorUtils.execute(DatabasePopulatorUtils.java:48) ~[spring-jdbc-4.2.1.RELEASE.jar:4.2.1.RELEASE]
	at org.springframework.boot.autoconfigure.jdbc.DataSourceInitializer.runScripts(DataSourceInitializer.java:155) ~[spring-boot-autoconfigure-1.3.0.M5.jar:1.3.0.M5]
	at org.springframework.boot.autoconfigure.jdbc.DataSourceInitializer.runDataScripts(DataSourceInitializer.java:112) ~[spring-boot-autoconfigure-1.3.0.M5.jar:1.3.0.M5]
	at org.springframework.boot.autoconfigure.jdbc.DataSourceInitializer.onApplicationEvent(DataSourceInitializer.java:105) ~[spring-boot-autoconfigure-1.3.0.M5.jar:1.3.0.M5]
	at org.springframework.boot.autoconfigure.jdbc.DataSourceInitializer.onApplicationEvent(DataSourceInitializer.java:46) ~[spring-boot-autoconfigure-1.3.0.M5.jar:1.3.0.M5]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:163) ~[spring-context-4.2.1.RELEASE.jar:4.2.1.RELEASE]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:136) ~[spring-context-4.2.1.RELEASE.jar:4.2.1.RELEASE]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:119) ~[spring-context-4.2.1.RELEASE.jar:4.2.1.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.registerListeners(AbstractApplicationContext.java:804) ~[spring-context-4.2.1.RELEASE.jar:4.2.1.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:534) ~[spring-context-4.2.1.RELEASE.jar:4.2.1.RELEASE]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:118) ~[spring-boot-1.3.0.M5.jar:1.3.0.M5]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:667) [spring-boot-1.3.0.M5.jar:1.3.0.M5]
	at org.springframework.boot.SpringApplication.doRun(SpringApplication.java:342) [spring-boot-1.3.0.M5.jar:1.3.0.M5]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:273) [spring-boot-1.3.0.M5.jar:1.3.0.M5]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:980) [spring-boot-1.3.0.M5.jar:1.3.0.M5]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:969) [spring-boot-1.3.0.M5.jar:1.3.0.M5]
	at com.sivalabs.blog.BlogApplication.main(BlogApplication.java:21) [classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_45]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_45]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_45]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[na:1.8.0_45]
	at org.springframework.boot.devtools.restart.RestartLauncher.run(RestartLauncher.java:49) [spring-boot-devtools-1.3.0.M5.jar:1.3.0.M5]
```

**Comment by JavaHelper** [comment]
Simply we can increase Column size length to 100.

**Comment by sivaprasadreddy** [comment]
I have made the changes to fix it. Please pull latest.
